apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: frontend
        image: rajwanshbhati/thirdrepo:01
        ports:
        - containerPort: 5173

      - name: backend
        image: rajwanshbhati/thirdrepo:02
        ports:
        - containerPort: 4000

      - name: mongo
        image: mongo:4.4.18
        ports:
        - containerPort: 27017 

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
 type: NodePort 
selector:
    app: my-app
ports:
   - name: frontend-port
protocol: TCP
port: 8080         
targetPort: 5173  
nodePort: 30007 
