# # Deployment with Frontend, Backend, MongoDB
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: my-app
#   labels:
#     app: my-app
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: my-app
#   template:
#     metadata:
#       labels:
#         app: my-app
#     spec:
#       containers:
#         - name: frontend
#           image: rajwanshbhati/thirdrepo:frontend_08
#           ports:
#             - containerPort: 5173

#         - name: backend
#           image: rajwanshbhati/thirdrepo:backend_08
#           ports:
#             - containerPort: 4000

#         - name: mongo
#           image: mongo:4.4.18
#           ports:
#             - containerPort: 27017

# ---

# # Service to expose backend port 4000
# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-service
# spec:
#   type: NodePort
#   selector:
#     app: my-app
#   ports:
#     - name: backend-port
#       protocol: TCP
#       port: 4000        # Cluster port
#       targetPort: 4000  # Container port
#       nodePort: 30008   # External NodePort (optional)
# Deployment with Frontend, Backend, MongoDB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: frontend
          image: rajwanshbhati/thirdrepo:frontend_08
          ports:
            - containerPort: 5173

        - name: backend
          image: rajwanshbhati/thirdrepo:backend_08
          ports:
            - containerPort: 4000

        - name: mongo
          image: mongo:4.4.18
          ports:
            - containerPort: 27017

---

# Service to expose backend port 4000
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - name: backend-port
      protocol: TCP
      port: 4000        # ClusterIP port (inside cluster)
      targetPort: 4000  # Matches backend container
      nodePort: 30008   # External NodePort

---

# Service to expose frontend port 5173
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - name: frontend-port
      protocol: TCP
      port: 5173        # ClusterIP port (inside cluster)
      targetPort: 5173  # Matches frontend container
     